version: '3'

services:
  app-name-local:
    build:
      context: ../../
      dockerfile: docker/local/Dockerfile
    image: app-name-local
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
